# Generated by Django 5.0 on 2024-04-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_product_detail_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
