# Generated by Django 5.0 on 2024-04-09 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_userclickcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserClickCount',
        ),
    ]
