# Generated by Django 5.0 on 2024-04-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_delete_userclickcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='save_clicked',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
